module.exports = [
    {
        name:"公司名称",
        key:"companyName",
        required:true
    },
    {
        name:"公司地址",
        key:"companyAddress",
        required:true,
    },
    {
        name:"公司税号",
        key:"taxNo",
        or:"registerNo",
        required:true
    },
    {
        name:"公司注册码",
        key:"registerNo",
        or:"taxNo",
    },
    {
        name:"联系人姓名",
        key:"contackPerson",
        required:true
    },
    {
        name:"联系人邮箱",
        alternative:[
            "联系邮箱"
        ],
        key:"email",
        required:true
    },
    {
        name:"充值金额",
        key:"amount",
        required:true,
        type:"decimal",
        rules:[
            {
                name:"positive"
            }
            
        ]
    },
    {
        name:"汇款编号",
        key:"refNo",
        required:true
    },
    {
        name:"币种",
        key:"currency",
        required:true,
        default:"EUR",
        rules:[
           {
               name:"validString",
               params:["USD","EUR"]
           }
        ]

    }
]